export const actionOptions = [
  { value: null, label: "All Actions" },
  { value: "user.login", label: "User Login" },
  { value: "user.logout", label: "User Logout" },
  { value: "target.created", label: "Target Created" },
  { value: "target.updated", label: "Target Updated" },
  { value: "target.deleted", label: "Target Deleted" },
  { value: "alert.created", label: "Alert Created" },
  { value: "alert.status_changed", label: "Alert Status Changed" },
  { value: "alert.assigned", label: "Alert Assigned" },
  { value: "alert.comment_added", label: "Alert Comment Added" },
  { value: "alert.exported", label: "Alert Exported" },
  { value: "organization.member_invited", label: "Member Invited" },
  { value: "organization.member_removed", label: "Member Removed" },
  { value: "organization.member_role_changed", label: "Member Role Changed" },
  { value: "billing.subscription_created", label: "Subscription Created" },
  { value: "billing.subscription_updated", label: "Subscription Updated" },
  { value: "export.alerts", label: "Alerts Exported" },
];
