CREATE INDEX IF NOT EXISTS "alert_relationships_sourceAlertId_idx" ON "alert_relationships" USING btree ("sourceAlertId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "alert_relationships_targetAlertId_idx" ON "alert_relationships" USING btree ("targetAlertId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "alert_relationships_type_idx" ON "alert_relationships" USING btree ("relationshipType");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "alert_tag_assignments_alertId_idx" ON "alert_tag_assignments" USING btree ("alertId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "alert_tag_assignments_tagId_idx" ON "alert_tag_assignments" USING btree ("tagId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "alert_tags_organizationId_idx" ON "alert_tags" USING btree ("organizationId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "alert_templates_organizationId_idx" ON "alert_templates" USING btree ("organizationId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "alert_templates_category_idx" ON "alert_templates" USING btree ("category");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "alerts_organizationId_idx" ON "alerts" USING btree ("organizationId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "alerts_targetId_idx" ON "alerts" USING btree ("targetId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "alerts_versionId_idx" ON "alerts" USING btree ("versionId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "alerts_status_idx" ON "alerts" USING btree ("status");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "alerts_impactScore_idx" ON "alerts" USING btree ("impactScore");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "alerts_createdAt_idx" ON "alerts" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "alerts_snoozedUntil_idx" ON "alerts" USING btree ("snoozedUntil");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "alerts_organizationId_status_idx" ON "alerts" USING btree ("organizationId","status");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "alerts_organizationId_createdAt_idx" ON "alerts" USING btree ("organizationId","createdAt");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "api_keys_organizationId_idx" ON "api_keys" USING btree ("organizationId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "api_keys_userId_idx" ON "api_keys" USING btree ("userId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "api_keys_status_idx" ON "api_keys" USING btree ("status");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "custom_alert_rules_organizationId_idx" ON "custom_alert_rules" USING btree ("organizationId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "custom_alert_rules_status_idx" ON "custom_alert_rules" USING btree ("status");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "targets_organizationId_idx" ON "targets" USING btree ("organizationId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "targets_status_idx" ON "targets" USING btree ("status");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "targets_category_idx" ON "targets" USING btree ("category");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "targets_jurisdiction_idx" ON "targets" USING btree ("jurisdiction");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "usage_metrics_organizationId_idx" ON "usage_metrics" USING btree ("organizationId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "usage_metrics_metricType_idx" ON "usage_metrics" USING btree ("metricType");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "usage_metrics_recordedAt_idx" ON "usage_metrics" USING btree ("recordedAt");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "usage_metrics_organizationId_recordedAt_idx" ON "usage_metrics" USING btree ("organizationId","recordedAt");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "versions_targetId_idx" ON "versions" USING btree ("targetId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "versions_crawledAt_idx" ON "versions" USING btree ("crawledAt");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "webhook_configs_organizationId_idx" ON "webhook_configs" USING btree ("organizationId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "webhook_configs_status_idx" ON "webhook_configs" USING btree ("status");